name: repa-e
channels:
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - bzip2=1.0.8=h5eee18b_6
  - ca-certificates=2025.9.9=h06a4308_0
  - ld_impl_linux-64=2.44=h153f514_2
  - libexpat=2.7.1=hecca717_0
  - libffi=3.4.4=h6a678d5_1
  - libgcc=15.2.0=h767d61c_7
  - libgcc-ng=15.2.0=h69a702a_7
  - libgomp=15.2.0=h767d61c_7
  - liblzma=5.8.1=hb9d3cd8_2
  - libnsl=2.0.1=hb9d3cd8_1
  - libsqlite=3.50.4=h0c1763c_0
  - libstdcxx-ng=11.2.0=h1234567_1
  - libuuid=2.41.2=he9a06e4_0
  - libxcb=1.17.0=h9b100fa_0
  - libxcrypt=4.4.36=hd590300_1
  - libzlib=1.3.1=hb25bd0a_0
  - ncurses=6.5=h7934f7d_0
  - openssl=3.5.4=h26f9b46_0
  - pip=25.2=pyhc872135_1
  - pthread-stubs=0.3=h0ce48e5_1
  - python=3.10.17=hd6af730_0_cpython
  - readline=8.3=hc2a1206_0
  - setuptools=80.9.0=py310h06a4308_0
  - tk=8.6.15=h54e0aa7_0
  - tzdata=2025b=h04d1e81_0
  - wheel=0.45.1=py310h06a4308_0
  - xorg-libx11=1.8.12=h9b100fa_1
  - xorg-libxau=1.0.12=h9b100fa_0
  - xorg-libxdmcp=1.1.5=h9b100fa_0
  - xorg-xorgproto=2024.1=h5eee18b_1
  - zlib=1.3.1=hb25bd0a_0
  - pip:
      - accelerate==1.1.1
      - antlr4-python3-runtime==4.9.3
      - certifi==2025.1.31
      - charset-normalizer==3.4.1
      - click==8.1.8
      - git+https://github.com/openai/CLIP.git
      - dictdot==1.5.1
      - docker-pycreds==0.4.0
      - einops==0.8.0
      - filelock==3.18.0
      - fsspec==2025.3.0
      - ftfy==6.3.1
      - gitdb==4.0.12
      - gitpython==3.1.44
      - h5py==3.12.1
      - huggingface-hub==0.29.3
      - idna==3.10
      - jinja2==3.1.6
      - markupsafe==3.0.2
      - mpmath==1.3.0
      - networkx==3.2.1
      - numpy==1.26.4
      - nvidia-cublas-cu12==12.1.3.1
      - nvidia-cuda-cupti-cu12==12.1.105
      - nvidia-cuda-nvrtc-cu12==12.1.105
      - nvidia-cuda-runtime-cu12==12.1.105
      - nvidia-cudnn-cu12==8.9.2.26
      - nvidia-cufft-cu12==11.0.2.54
      - nvidia-curand-cu12==10.3.2.106
      - nvidia-cusolver-cu12==11.4.5.107
      - nvidia-cusparse-cu12==12.1.0.106
      - nvidia-nccl-cu12==2.20.5
      - nvidia-nvjitlink-cu12==12.8.93
      - nvidia-nvtx-cu12==12.1.105
      - omegaconf==2.3.0
      - packaging==24.2
      - pillow==11.1.0
      - platformdirs==4.3.7
      - protobuf==5.29.4
      - psutil==7.0.0
      - pyyaml==6.0.2
      - regex==2024.11.6
      - requests==2.32.3
      - safetensors==0.5.3
      - sentry-sdk==2.24.0
      - setproctitle==1.3.5
      - six==1.17.0
      - smmap==5.0.2
      - sympy==1.13.3
      - timm==1.0.11
      - tokenizers==0.20.3
      - torch==2.3.1
      - torchvision==0.18.1
      - tqdm==4.67.1
      - transformers==4.46.3
      - triton==2.3.1
      - typing-extensions==4.12.2
      - urllib3==2.3.0
      - wandb==0.18.7
      - wcwidth==0.2.13
