# model params
# model_name_or_path: stablediffusionapi/juggernaut-reborn 
model_name_or_path: stabilityai/sd-turbo
# dataset_name: lambdalabs/naruto-blip-captions
dataset_name: dim/nfs_pix2pix_1920_1080_v5
seed: 2025

output_dir: checkpoints/auto_remaster/sd1.5_ddpm 
learning_rate: 5e-6 
use_ema: false 
max_grad_norm: 1 
lr_scheduler_type: "constant"
warmup_steps: 0 
report_to: wandb
warmup_steps: 500
weight_decay: 1e-2


# train optimization
# eval_on_start: true
resume_from_checkpoint: false
eval_on_start: false
resolution: 512
per_device_train_batch_size: 4 
gradient_accumulation_steps: 1 
gradient_checkpointing: false 

# save params
save_steps: 200
max_steps: 15000 

# diffusion params
source_image_name: input_image
target_image_name: edited_image
caption_column: edit_prompt
num_inference_steps: 1
cache_dir: dataset/nfs_pix2pix_1920_1080_v5
noise_scheduler_type: stabilityai/sd-turbo